--THIS IS SECRET 2 FOR POSTGRES --
apiVersion: v1
kind: Secret
metadata:
  name: superset-env
  labels:
    app: superset
    chart: superset-0.6.3
    release: "superset"
    heritage: "Helm"
type: Opaque
stringData:
    REDIS_HOST: "superset-redis-headless"
    REDIS_PORT: "6379"
    DB_HOST: "superset-postgresql"
    DB_PORT: "5432"
    DB_USER: "superset"
    DB_PASS: "superset"
    DB_NAME: "superset"