--THIS IS SECRET FOR POSTGRES NUMBER 1 --
# Source: superset/charts/postgresql/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: superset-postgresql
  namespace: "default"
  labels:
    app.kubernetes.io/name: postgresql
    helm.sh/chart: postgresql-11.1.22
    app.kubernetes.io/instance: superset
    app.kubernetes.io/managed-by: Helm
type: Opaque
data:
  postgres-password: "NGFZcXJVSGdIOA=="
  password: "c3VwZXJzZXQ="